CREATE TABLE account (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    money DOUBLE DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
INSERT INTO account VALUES (1, 'aaa', 1000);
INSERT INTO account VALUES (2, 'bbb', 1000);
INSERT INTO account VALUES (3, 'ccc', 1000);

UPDATE account SET money = 1000 WHERE id IS NOT NULL;

